# Generated by Django 4.2.7 on 2023-11-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_phone_number_employee_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='first_name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
