# Generated by Django 4.2.7 on 2023-11-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_first_name_employer_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
    ]
