# Generated by Django 4.2.7 on 2023-11-20 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_employerprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('education_requirements', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('freelance', 'Freelance'), ('permanent', 'Permanent'), ('contract', 'Contract'), ('remote', 'Remote'), ('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=20, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.employerprofile')),
            ],
        ),
    ]
