# Generated by Django 4.2.7 on 2023-11-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_job_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ManyToManyField(to='jobs.categories'),
        ),
    ]
